---
title: "01-benefit-per-person"
author: "Juliane Kloidt"
date: "2025-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# set the workspace path to the directory containing this script
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# clear the environment
rm(list=ls())

library(tidyverse)

data <- read_csv("data/data-scotland.csv") %>%
  select(-c(damage_pathway, damage_type, households, nation))
```

```{r}
# combine co-benefits for each factor, grouped by local authority, and small area
data_benefit_factor <- data %>% group_by(local_authority, small_area, `co-benefit_type`, population) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)))

# combine co-benefits across all factors, grouped by local authority, and small area
data_benefit_sum <- data %>% group_by(local_authority, small_area, population) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)))

## missing data for small_area == S01010206 and `co-benefit_type` == hassle_costs

# combine co-benefits across all factors and across small areas, grouped by local authority
data_benefit_sum_authority <- data %>% group_by(local_authority, small_area, population) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>% ungroup() %>%
  group_by(local_authority) %>% summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)))

# sum of co-benefits for each local authority
ggplot(data_benefit_sum_authority, aes(y=sum, x = local_authority)) +
  geom_col() + ylab("Benefits per local authority (Million GBP)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank())


```

# Research Question 1
```{r}
# sum of co-benefits for each local authority weighted by population
data_benefit_sum_authority %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  ggplot(., aes(y=sum_weighted, x = local_authority)) +
  theme_classic()+
  geom_col() + ylab("Benefits per person (GBP)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank())

# distribution
data_benefit_sum_authority %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  ggplot(., aes(x=sum_weighted)) +
  geom_density()

# summary statistics
data_benefit_sum_authority %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  select(local_authority, sum_weighted) %>%
  summarise(mean = mean(sum_weighted),
            median = median(sum_weighted),
            sd = sd(sum_weighted),
            min = min(sum_weighted),
            max= max(sum_weighted))
```


```{r}
# plot trajectory of benefits for each local authority
data_benefit_authority_long <- data_benefit_sum_authority %>% 
  select(-c(population, sum)) %>%
  pivot_longer(cols = -c(local_authority), names_to = "year", values_to = "benefits")
  
ggplot(data_benefit_authority_long, aes(x=year, y=benefits, group = local_authority, color = local_authority)) +
  theme_minimal() +
  geom_line()
# big city have the largest benefits (because they have most inhabitants)

# plot trajectory of benefits for each local authority WEIGHTED BY POPULATION
data_benefit_authority_long_weighted <- data_benefit_sum_authority %>% 
  rowwise() %>% mutate(across(c(`2025`:`2050`), .fns = ~./population)) %>%
  select(-c(population, sum)) %>%
  pivot_longer(cols = -c(local_authority), names_to = "year", values_to = "benefits")

ggplot(data_benefit_authority_long_weighted, 
       aes(x=year, y=benefits, group = local_authority, color = local_authority)) +
  theme_minimal() +
  geom_line()
# there seems to be several groups of authorities: 
# some increase strongly and then decrease, others increase more continuously
# 0.00010 billion is 0.1 million is 100K benefit per person

# try to spot patterns in which local authorities have a spike in benefits, and which have a gradual increase
# rural / islands show spike > they would immediately benefit from net zero
# cities (Glasgow, Edinburgh, Dundee, Aberdeen, are very similar)
ggplot(data_benefit_authority_long_weighted, 
       aes(x=year, y=benefits, group = local_authority, color = local_authority)) +
  theme_minimal() +
  geom_line() +
  facet_wrap(~local_authority) +
  theme(legend.position = "none",
        axis.text.x = element_blank())

# questions: are there distinct groups of local authorities (rural vs urban)
# OR does the trajectory of co-benefits depend mostly on population (e.g., 100K+ vs. 100K-) > Stirling is under 100K
# OR does the trajectory of co-benefits depend on geographical location (e.g., north vs south)


```


