---
title: "01a-maps-scotland"
author: "Juliane Kloidt"
date: "2025-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# set the workspace path to the directory containing this script
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# clear the environment
rm(list=ls())

library(tidyverse)
library(sf)
library(viridis)

data <- read_csv("data/data-scotland.csv") %>%
  select(-c(damage_pathway, damage_type, households, nation))

# local authorities
grid <- st_read("data/pub_las.shx")

```

# Data prep
```{r}
# combine co-benefits for each factor, grouped by local authority, and small area
data_benefit_factor <- data %>% group_by(local_authority, small_area, `co-benefit_type`, population) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)))
```

# Local Authorities
Visualize the sum of all co-benefits and the top 5 co-benefits for Scotland by local authority

## Sum of co-benefits
```{r}
# visualize the results as a map of Scotland
# check if there are meaningful differences between rural vs. urban local authorities
data_test <- data %>% group_by(local_authority, small_area, population) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>% ungroup() %>%
  group_by(local_authority) %>% summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>%
  mutate(local_auth = 
           case_when(local_authority == "Na h-Eileanan Siar" ~ "Na h-Eileanan an Iar",
                     TRUE ~ local_authority)) %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  select(local_auth, sum_weighted)

# plot shape file filled by sum variable
grid_comb <- left_join(grid, data_test)

```

```{r}
ggplot(data=grid_comb) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  # add titles
  labs(x = NULL,
         y = NULL,
         title = "Scotland's Co-Benefits from Reaching Net Zero",
         subtitle = "Sum of Co-Benefits per Capita, 2025-2050",
         caption = "Map CC-BY-SA; Code: github.com/JulianeKloidt/dataviz_competition2025 \n 
       Author: Juliane Kloidt; Geometries: Spatial Hub Scotland; Data: ECCI")

ggsave(filename = "figures/fig-map-scotland-ALL-FACTORS.png", 
       bg="white", width = 210, height = 180, units = "mm")
```

## Physical Activity
```{r}
data_pa <- data_benefit_factor %>% 
  select(local_authority, `co-benefit_type`, population, sum) %>%
  filter(`co-benefit_type`=="physical_activity") %>%
  group_by(local_authority) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  mutate(local_auth = 
           case_when(local_authority == "Na h-Eileanan Siar" ~ "Na h-Eileanan an Iar",
                     TRUE ~ local_authority)) %>%
  select(local_auth, sum_weighted)

# plot shape file filled by sum variable
grid_pa <- left_join(grid, data_pa)

ggplot(data=grid_pa) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  # add titles
  labs(x = NULL,
         y = NULL,
         title = "Scotland's Physical Activity Co-Benefits",
         subtitle = "Sum of Co-Benefits from Physical Activity per Capita, 2025-2050")

ggsave(filename = "figures/fig-map-scotland-PHYSICAL-ACTIVITY.png", 
       bg="white", width = 210, height = 180, units = "mm")
```

## Noise
```{r}
data_noise <- data_benefit_factor %>% 
  select(local_authority, `co-benefit_type`, population, sum) %>%
  filter(`co-benefit_type`=="noise") %>%
  group_by(local_authority) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  mutate(local_auth = 
           case_when(local_authority == "Na h-Eileanan Siar" ~ "Na h-Eileanan an Iar",
                     TRUE ~ local_authority)) %>%
  select(local_auth, sum_weighted)

# plot shape file filled by sum variable
grid_noise <- left_join(grid, data_noise)

ggplot(data=grid_noise) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  # add titles
  labs(x = NULL,
         y = NULL,
         title = "Scotland's Noise Co-Benefits",
         subtitle = "Sum of Co-Benefits from PNoise per Capita, 2025-2050")

ggsave(filename = "figures/fig-map-scotland-NOISE.png", 
       bg="white", width = 210, height = 180, units = "mm")
```

## Air quality
```{r}
data_air <- data_benefit_factor %>% 
  select(local_authority, `co-benefit_type`, population, sum) %>%
  filter(`co-benefit_type`=="air_quality") %>%
  group_by(local_authority) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  mutate(local_auth = 
           case_when(local_authority == "Na h-Eileanan Siar" ~ "Na h-Eileanan an Iar",
                     TRUE ~ local_authority)) %>%
  select(local_auth, sum_weighted)

# plot shape file filled by sum variable
grid_air <- left_join(grid, data_air)

ggplot(data=grid_air) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  # add titles
  labs(x = NULL,
         y = NULL,
         title = "Scotland's Air Quality Co-Benefits",
         subtitle = "Sum of Co-Benefits from Air Quality per Capita, 2025-2050")

ggsave(filename = "figures/fig-map-scotland-AIR-QUALITY.png", 
       bg="white", width = 210, height = 180, units = "mm")
```

## Diet Change
```{r}
data_diet <- data_benefit_factor %>% 
  select(local_authority, `co-benefit_type`, population, sum) %>%
  filter(`co-benefit_type`=="diet_change") %>%
  group_by(local_authority) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  mutate(local_auth = 
           case_when(local_authority == "Na h-Eileanan Siar" ~ "Na h-Eileanan an Iar",
                     TRUE ~ local_authority)) %>%
  select(local_auth, sum_weighted)

# plot shape file filled by sum variable
grid_diet <- left_join(grid, data_diet)

ggplot(data=grid_diet) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  # add titles
  labs(x = NULL,
         y = NULL,
         title = "Scotland's Diet Change Co-Benefits",
         subtitle = "Sum of Co-Benefits from Diet Change per Capita, 2025-2050")

ggsave(filename = "figures/fig-map-scotland-DIET-CHANGE.png", 
       bg="white", width = 210, height = 180, units = "mm")
```

## Excess Cold
```{r}
data_cold <- data_benefit_factor %>% 
  select(local_authority, `co-benefit_type`, population, sum) %>%
  filter(`co-benefit_type`=="excess_cold") %>%
  group_by(local_authority) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  mutate(local_auth = 
           case_when(local_authority == "Na h-Eileanan Siar" ~ "Na h-Eileanan an Iar",
                     TRUE ~ local_authority)) %>%
  select(local_auth, sum_weighted)

# plot shape file filled by sum variable
grid_cold <- left_join(grid, data_cold)

ggplot(data=grid_cold) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  # add titles
  labs(x = NULL,
         y = NULL,
         title = "Scotland's Excess Cold Co-Benefits",
         subtitle = "Sum of Co-Benefits from Excess Cold per Capita, 2025-2050")

ggsave(filename = "figures/fig-map-scotland-EXCESS-COLD.png", 
       bg="white", width = 210, height = 180, units = "mm")
```
