---
title: "1b-maps-glasgow"
author: "Juliane Kloidt"
date: "2025-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# set the workspace path to the directory containing this script
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# clear the environment
rm(list=ls())

library(tidyverse)
library(sf)
library(viridis)

data <- read_csv("data/data-scotland.csv") %>%
  select(-c(damage_pathway, damage_type, households, nation))

# combine co-benefits for each factor, grouped by local authority, and small area
data_benefit_factor <- data %>% group_by(local_authority, small_area, `co-benefit_type`, population) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)))

# small areas + SIMD
Ggrid <- st_read("data/SG_SIMD_2020.shx")

```

# Glasgow City
Visualize the Scottish Index of Multiple Deprivation (SIMD) for Glasgow City by small area code
Visualize the sum of all co-benefits and the top 5 co-benefits for Glasgow City by small area code

## SIMD
```{r}
Ggrid_glasgow <- Ggrid %>% filter(LAName == "Glasgow City")

# SIMD
ggplot(Ggrid_glasgow) +
  geom_sf(mapping = aes(fill=Percentv2), color="white") +
# THE LOWER THE PERCENTAGE THE MORE DEPRIVED THE AREA
  scale_fill_viridis(
    option = "magma",
    name = "Percentile",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is more deprived, yellow is less deprived
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  labs(x = NULL, y = NULL,
         title = "Glasgow's Index of Multiple Deprivation",
         subtitle = "Scottish Index of Multiple Deprivation in Glasgow City, 2020"
       )
  

ggsave(filename = "figures/fig-map-glasgow-SIMD.png", bg="white", width = 180, height = 120, units = "mm")
```

## Sum of co-benefits
```{r}
data_sum <- data_benefit_factor %>% 
  filter(local_authority=="Glasgow City") %>%
  group_by(local_authority, small_area, population) %>%
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE))) %>% ungroup() %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  ungroup() %>%
  rename("DataZone" = "small_area") %>%
  select(DataZone, population, sum_weighted)

grid_glasgow_sum <- left_join(Ggrid_glasgow, data_sum)

ggplot(grid_glasgow_sum) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
# THE HIGHER THE SUM THE MORE BENEFITS
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  labs(x = NULL, y = NULL,
         title = "Eleven Co-Benefits per Capita",
         subtitle = "Scotland's Co-Benefits from Reaching Net Zero, 2025 to 2050"
       )

ggsave(filename = "figures/fig-map-glasgow-ALL-FACTORS.png", bg="white", width = 180, height = 120, units = "mm")


```

## Physical activity
```{r}
data_pa <- data_benefit_factor %>% filter(`co-benefit_type`=="physical_activity") %>%
  filter(local_authority=="Glasgow City") %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  ungroup() %>%
  rename("DataZone" = "small_area") %>%
  select(DataZone, population, sum_weighted)

grid_glasgow_pa <- left_join(Ggrid_glasgow, data_pa)

ggplot(grid_glasgow_pa) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
# THE HIGHER THE SUM THE MORE BENEFITS
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  labs(x = NULL, y = NULL,
         title = "Physical Activity Benefits per Capita",
         subtitle = "Scotland's Co-Benefits from Reaching Net Zero, 2025 to 2050"
       )

ggsave(filename = "figures/fig-map-glasgow-PHYSICAL-ACTIVITY.png", bg="white", width = 180, height = 120, units = "mm")


```

## Noise
```{r}
data_noise <- data_benefit_factor %>% filter(`co-benefit_type`=="noise") %>%
  filter(local_authority=="Glasgow City") %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  ungroup() %>%
  rename("DataZone" = "small_area") %>%
  select(DataZone, population, sum_weighted)

grid_glasgow_noise <- left_join(Ggrid_glasgow, data_noise)

ggplot(grid_glasgow_noise) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
# THE HIGHER THE SUM THE MORE BENEFITS
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  labs(x = NULL, y = NULL,
         title = "Noise Benefits per Capita",
         subtitle = "Scotland's Co-Benefits from Reaching Net Zero, 2025 to 2050"
       )

ggsave(filename = "figures/fig-map-glasgow-NOISE.png", bg="white", width = 180, height = 120, units = "mm")


```

## Air quality
```{r}
data_air <- data_benefit_factor %>% filter(`co-benefit_type`=="air_quality") %>%
  filter(local_authority=="Glasgow City") %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  ungroup() %>%
  rename("DataZone" = "small_area") %>%
  select(DataZone, population, sum_weighted)

grid_glasgow_air <- left_join(Ggrid_glasgow, data_air)

ggplot(grid_glasgow_air) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
# THE HIGHER THE SUM THE MORE BENEFITS
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  labs(x = NULL, y = NULL,
         title = "Air Quality Benefits per Capita",
         subtitle = "Scotland's Co-Benefits from Reaching Net Zero, 2025 to 2050"
       )

ggsave(filename = "figures/fig-map-glasgow-AIR-QUALITY.png", bg="white", width = 180, height = 120, units = "mm")


```

## Diet Change
```{r}
data_diet <- data_benefit_factor %>% filter(`co-benefit_type`=="diet_change") %>%
  filter(local_authority=="Glasgow City") %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  ungroup() %>%
  rename("DataZone" = "small_area") %>%
  select(DataZone, population, sum_weighted)

grid_glasgow_diet <- left_join(Ggrid_glasgow, data_diet)

ggplot(grid_glasgow_diet) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
# THE HIGHER THE SUM THE MORE BENEFITS
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  labs(x = NULL, y = NULL,
         title = "Diet Change Benefits per Capita",
         subtitle = "Scotland's Co-Benefits from Reaching Net Zero, 2025 to 2050"
       )

ggsave(filename = "figures/fig-map-glasgow-DIET-CHANGE.png", bg="white", width = 180, height = 120, units = "mm")


```

## Excess Cold
```{r}
data_cold <- data_benefit_factor %>% filter(`co-benefit_type`=="excess_cold") %>%
  filter(local_authority=="Glasgow City") %>%
  mutate(sum_weighted = (sum/population)*1000000) %>%
  ungroup() %>%
  rename("DataZone" = "small_area") %>%
  select(DataZone, population, sum_weighted)

grid_glasgow_cold <- left_join(Ggrid_glasgow, data_cold)

ggplot(grid_glasgow_cold) +
  geom_sf(mapping = aes(fill=sum_weighted), color="white")+
# THE HIGHER THE SUM THE MORE BENEFITS
  scale_fill_viridis(
    option = "magma",
    name = "Co-Benefits in GBP",
    alpha = 0.8, # make fill a bit brighter
    begin = 0.1, 
    end = 0.9,
    discrete = F,
    direction = 1, # dark is lowest, yellow is highest
    guide = guide_colorbar(
     keyheight = unit(30, units = "mm"),
     title.position = "top",
     reverse = F # display highest co-benefits on top
  )) +
  labs(x = NULL, y = NULL,
         title = "Excess Cold Benefits per Capita",
         subtitle = "Scotland's Co-Benefits from Reaching Net Zero, 2025 to 2050"
       )

ggsave(filename = "figures/fig-map-glasgow-EXCESS-COLD.png", bg="white", width = 180, height = 120, units = "mm")


```